spring.application.name=JLAutomate_Backend

# --- Config DB ---
spring.datasource.url=jdbc:postgresql://localhost:5432/JLAutomate
spring.datasource.username=appuser
spring.datasource.password=apppass

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port du backend
server.port=8080
